# Generated by Django 5.0.2 on 2024-03-02 18:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_setting_aboutus_alter_setting_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
