# Generated by Django 5.0.2 on 2024-03-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_setting_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='smtport',
            new_name='smtpport',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='updated',
            new_name='update_at',
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
