# Generated by Django 5.0.2 on 2024-03-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_lft'),
        ('product', '0006_product_reviewscount'),
    ]

    operations = [
    ]
